language: node_js
node_js:
  - "node"

notifications:
  webhooks:
    urls:
      - https://blackbox.schrottfresse.de/github/
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: always
    on_cancel: always # default: always
    on_error: always # default: always
